//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patterns.Repository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceLine
    {
        public int Id { get; set; }
        public int InvoiceID { get; set; }
        public int StockItemID { get; set; }
        public decimal NumberOfUnits { get; set; }
        public decimal NetLinePriceAdjustment { get; set; }
        public int Ordinal { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual StockItem StockItem { get; set; }
    }
}
