/*
Deployment script for Patterns_Repository_DB

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "Patterns_Repository_DB"
:setvar DefaultFilePrefix "Patterns_Repository_DB"
:setvar DefaultDataPath "C:\Users\Nathan\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\ProjectsV12\"
:setvar DefaultLogPath "C:\Users\Nathan\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\ProjectsV12\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[Table].[Adjustment] (SqlSimpleColumn) will not be renamed to NetLinePriceAdjustment';


GO

IF (SELECT OBJECT_ID('tempdb..#tmpErrors')) IS NOT NULL DROP TABLE #tmpErrors
GO
CREATE TABLE #tmpErrors (Error int)
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
GO
BEGIN TRANSACTION
GO
PRINT N'Creating [dbo].[InvoiceLine]...';


GO
CREATE TABLE [dbo].[InvoiceLine] (
    [Id]                     INT             IDENTITY (1, 1) NOT NULL,
    [InvoiceID]              INT             NOT NULL,
    [StockItemID]            INT             NOT NULL,
    [NumberOfUnits]          NUMERIC (18, 4) NOT NULL,
    [NetLinePriceAdjustment] NUMERIC (18, 4) NOT NULL,
    [Ordinal]                INT             NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating unnamed constraint on [dbo].[InvoiceLine]...';


GO
ALTER TABLE [dbo].[InvoiceLine]
    ADD DEFAULT 0 FOR [NetLinePriceAdjustment];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[FK_InvoiceLine_Invoice]...';


GO
ALTER TABLE [dbo].[InvoiceLine] WITH NOCHECK
    ADD CONSTRAINT [FK_InvoiceLine_Invoice] FOREIGN KEY ([InvoiceID]) REFERENCES [dbo].[Invoice] ([Id]);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[FK_InvoiceLine_StockItem]...';


GO
ALTER TABLE [dbo].[InvoiceLine] WITH NOCHECK
    ADD CONSTRAINT [FK_InvoiceLine_StockItem] FOREIGN KEY ([StockItemID]) REFERENCES [dbo].[StockItem] ([Id]);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO

IF EXISTS (SELECT * FROM #tmpErrors) ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT>0 BEGIN
PRINT N'The transacted portion of the database update succeeded.'
COMMIT TRANSACTION
END
ELSE PRINT N'The transacted portion of the database update failed.'
GO
DROP TABLE #tmpErrors
GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[InvoiceLine] WITH CHECK CHECK CONSTRAINT [FK_InvoiceLine_Invoice];

ALTER TABLE [dbo].[InvoiceLine] WITH CHECK CHECK CONSTRAINT [FK_InvoiceLine_StockItem];


GO
PRINT N'Update complete.';


GO
